name: project_euler
dependencies:
  - python=3.7
  - pip>19.0
  - certifi
  - setuptools
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - matplotlib
  - numba
  - colorama

