
import math
import numpy as np

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""


def tri_generator(n: int=1):
    while True:
        yield int(n*(n+1)/2)
        n += 1


def is_pentagonal(n: int):
    if n >= 0:
        k = (math.sqrt(24*n+1)+1)/6
        return k.is_integer()
    else:
        return False

def is_hexagonal(n: int):
    if n >= 0:
        k = (math.sqrt(8*n+1)+1)/4
        return k.is_integer()
    else:
        return False


## generator of triangular and check if is hexagonal AND pentagonal
tri_n, x = 286, 0
genr = tri_generator(tri_n)
while True:
    x = next(genr)
    if is_hexagonal(x) and is_pentagonal(x):
        print('Found! {0}'.format(x))
        break
    elif x % 1000 == 0:
        print("current val: {0}".format(x))







